version: '1.0'
services:
  payroll_loadgen:
    image: loadgen-payroll:v1    Maps host port 8080 to container port 8080
    environment:
      - BASE_URL=http://payrollmngmt_app:8080
    depends_on:
      - payrollmngmt_app