apiVersion: apps/v1
kind: Deployment
metadata:
  name: payrollmngmt
  namespace: payrollmngmt
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payrollmngmt
  template:
    metadata:
      labels:
        app: payrollmngmt
    spec:
      containers:
      - name: payrollmngmt
        image: michaelstephan/payrollmngmt:0.0.1
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_APPLICATION_NAME
          value: "payrollmngmt"