apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payrollmngmt-ingress
  namespace: payrollmngmt
spec:
  rules:
    - host: payrollmngmt.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: payrollmngmt-service
                port:
                  number: 80
  tls:
    - hosts:
        - payrollmngmt.example.com
      secretName: payrollmngmt-tls-secret